language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

before_install:
  Rscript -e 'update.packages(ask = FALSE)'
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
